In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
data = np.genfromtxt('raw_data.txt', delimiter = ',')
X = data[:,:4]
y = data[:, 4]
print(X)
print(y)

[[  3.6216    8.6661   -2.8073   -0.44699]
 [  4.5459    8.1674   -2.4586   -1.4621 ]
 [  3.866    -2.6383    1.9242    0.10645]
 ...
 [ -3.7503  -13.4586   17.5932   -2.7771 ]
 [ -3.5637   -8.3827   12.393    -1.2823 ]
 [ -2.5419   -0.65804   2.6842    1.1952 ]]
[0. 0. 0. ... 1. 1. 1.]
